### ISSUE TITLE
I met shape problem.

### ISSUE THREAD

**Issue by Embedding** [peter3125/sentence2vec#10]
Thank you for this great project.
I met the following problem when I ran python3 spacy_sentence2vec_demo.py

Traceback (most recent call last):
  File "spacy_sentence2vec_demo.py", line 63, in <module>
    sentence_vectors = sentence_to_vec(sentence_list, embedding_size)  # all vectors converted together
  File "/home/zhaozhe/Desktop/opennmt/sentence2vec-master/sentence2vec.py", line 79, in sentence_to_vec
    pca.fit(np.array(sentence_set))
  File "/usr/local/lib/python3.5/dist-packages/sklearn/decomposition/pca.py", line 329, in fit
    self._fit(X)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/decomposition/pca.py", line 370, in _fit
    copy=self.copy)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py", line 441, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

I am looking forward to your reply!

**Comment by Embedding** [comment]
I have tried `pca.fit(np.array(sentence_set).reshape(1, -1))` and `pca.fit(np.array(sentence_set).reshape(1, -1))` in line 79, in sentence_to_vec. But they don't work.

**Comment by Embedding** [comment]
I have found the problem. I use `nlp = spacy.load('en_core_web_sm')` instead of `nlp = spacy.load('en_core_web_lg')` . Now the program goes well.

**Comment by rock3125** [comment]
haha - thanks  :+1:
